name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout del Código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar Dependencias
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          npm install --package-lock-only
          npm install
          # Forzamos la reparación de lo que quede pendiente
          npm audit fix --force

      - name: 🔒 Verificar Compliance
        run: npm audit --audit-level=high

      - name: 🧪 Ejecutar Pruebas Automatizadas
        run: npm test
